### PR TITLE
Bump version to v2.1.0

### PR DESCRIPTION
**Pull request by fernahh**
- Remove unecessary image from README
- Bump version of `package.json` and `bower.json`
- Add files with changes of #44 and #44 

@ContaAzul/domphysis

### CODE REVIEW

**Comment by cacontinuos** [comment]
@fernahh, thanks for your PR! By analyzing the blame information on this pull request, we identified @matheuspoleza and @caarlos0 to be potential reviewers

**Comment by cacontinuos** [comment]
You changed source files, but no tests were changed.

It might be OK if this is a refactory and no behavior has changed,
otherwise, please add a test to guarantee that your code works.

**Comment by thiagogodoy** [comment]
++

**Comment by cirocfc** [comment]
++

**Comment by caarlos0** [comment]
I think you can also remove the file `assets/images/credit-card-logo.png`

**Comment by fernahh** [comment]
@caarlos0 

screenshot from 2016-08-22 14-51-57

**Comment by caarlos0** [comment]
@fernahh huh, Im blind 💃

**Pull request merged**
