### PR TITLE
English improvements

### PR DESCRIPTION
**Pull request by caarlos0**
Improving wording and the like.

### CODE REVIEW

**Comment by cacontinuos** [comment]
By analyzing the blame information on this pull request, we identified @fernahh to be a potential reviewer

**Comment by pedrofurst** [comment]
+1

**Comment by fernahh** [comment]
++

**Comment by brunomanzo** [comment]
++

**Comment by matheuspoleza** [comment]
+1

**Comment by cacontinuos** [comment]
-1

PR should have a **good** description!

**Pull request merged**
