### PR TITLE
change name for security

### PR DESCRIPTION
**Pull request by pedrofurst**
* Change name secury for security

### CODE REVIEW

**Comment by cacontinuos** [comment]
By analyzing the blame information on this pull request, we identified @fernahh to be a potential reviewer

**Comment by cacontinuos** [comment]
-1

PR should have a **good** description!

**Comment by VictorBogo** [comment]
+1

**Comment by alisson11** [comment]
+1

**Comment by fernahh** [comment]
++

**Comment by caarlos0** [comment]
++

**Pull request merged**
