### PR TITLE
Adds more usage examples and method signature

### PR DESCRIPTION
**Pull request by verzola**

### CODE REVIEW

**Comment by cacontinuos** [comment]
Please improve the description of your pull request.

You can, for example, fill this form:

1. If applied, this commit will... ?
2. Why is this change being made?
3. Provide links to any relevant tickets, URLs or other resources.

**Comment by cacontinuos** [comment]
By analyzing the blame information on this pull request, we identified @fernahh, @caarlos0 and @matheuspoleza to be potential reviewers

**Comment by matheuspoleza** [comment]
++ for me

**Comment by fernahh** [comment]
nice! :) 

++

**Comment by regisgiongo** [comment]
++ :rocket:

**Pull request merged**
