### PR TITLE
adding first release tag

### PR DESCRIPTION
**Pull request by matheuspoleza**
- Changed release tag version
- Create LICENSE file

### CODE REVIEW

**Comment by cacontinuos** [comment]
By analyzing the blame information on this pull request, we identified @fernahh to be a potential reviewer

**Comment by fernahh** [comment]
@matheuspoleza tem trocar no bower também e rodar a task `npm run prepublish`.

**Comment by matheuspoleza** [comment]
@fernahh feito!

**Comment by fernahh** [comment]
@matheuspoleza now vai! hauahuehua

**Comment by cacontinuos** [comment]
-1

PR should have a **good** description!

**Pull request merged**
