### PR TITLE
Feature/update language - Fix method names

### PR DESCRIPTION
**Pull request by randalmaia**
screen shot 2016-01-29 at 4 35 55 pm

### CODE REVIEW

**Comment by cacontinuos** [comment]
By analyzing the blame information on this pull request, we identified @fernahh, @caarlos0 and @matheuspoleza to be potential reviewers

**Comment by caarlos0** [comment]
@randalmaia I think we should also replace `expiry` with `expiration`, which is the word used for credit cards after all.

**Comment by fernahh** [comment]
++

**Comment by hcarine** [comment]
++

**Comment by caarlos0** [comment]
thanks

**Pull request merged**
