### PR TITLE
Add improvements for npm build

### PR DESCRIPTION
**Pull request by fernahh**
- Exult travis manifest;
- Remove grunt, grunt-cli and grunt-contrib-clean;

Fix `build:clean` task with `rimraf` and add `-p` param on `mkdir` to
fix error on build.

- Update author on .banner.

### CODE REVIEW

**Comment by cacontinuos** [comment]
By analyzing the blame information on this pull request, we identified @matheuspoleza to be a potential reviewer

**Comment by matheuspoleza** [comment]
@fernahh  Delete gruntFile.js too

**Comment by matheuspoleza** [comment]
why you are changing release tag version each PR?

**Comment by matheuspoleza** [comment]
Change release, keep 1.0.0 for a while. ++

**Pull request merged**
