### PR TITLE
Remove unecessary files of gh-pages branch

### PR DESCRIPTION
**Pull request by fernahh**
The branch [gh-pages](https://github.com/ContaAzul/creditcard.js/tree/gh-pages) has unnecessary files of library. It should contain only files of website.

@ContaAzul/domphysis

### CODE REVIEW

**Comment by cacontinuos** [comment]
@fernahh, thanks for your PR! By analyzing the blame information on this pull request, we identified @caarlos0 and @matheuspoleza to be potential reviewers

**Comment by cacontinuos** [comment]
You changed source files, but no tests were changed.

It might be OK if this is a refactory and no behavior has changed,
otherwise, please add a test to guarantee that your code works.

**Comment by matheuspoleza** [comment]
+1

**Comment by caarlos0** [comment]
+1

**Comment by YosephCode** [comment]
++

**Pull request merged**
