### PR TITLE
Change build workflow.

### PR DESCRIPTION
**Pull request by fernahh**
- Remove rimraf
- Remove `clean` task.
- Bump version.

### CODE REVIEW

**Comment by cacontinuos** [comment]
By analyzing the blame information on this pull request, we identified @matheuspoleza to be a potential reviewer

**Comment by matheuspoleza** [comment]
-1 changed tag version again haha

**Comment by fernahh** [comment]
@matheuspoleza dessa vez eu quis, preciso publicar no npm pra testar! :)

**Comment by cacontinuos** [comment]
-1

PR should have a **good** description!

**Comment by matheuspoleza** [comment]
@fernahh publica uma pre-release então, 0.0.1

**Comment by fernahh** [comment]
@matheuspoleza foi!

**Pull request merged**
