### PR TITLE
Two digit expiration

### LINKED ISSUE #34: Expiration check fails
There are two issues with expiration date checking.

First is the line:

    if (yearLength < 2 && yearLength > 4) return false;

`yearLength` can't be both less than 2 and greater than 4.

Second is the line:

    return !(y < 1000 || y >= 3000);

This fails on two-digit expiration years, which are less than 1000.

### PR DESCRIPTION
**Pull request by jdforsythe**
This will fix #34

### CODE REVIEW

**Comment by cacontinuos** [comment]
By analyzing the blame information on this pull request, we identified @fernahh to be a potential reviewer

**Comment by cacontinuos** [comment]
You changed source files, but no tests were changed.

It might be OK if this is a refactory and no behavior has changed,
otherwise, please add a test to guarantee that your code works.

**Comment by jdforsythe** [comment]
Hmm, actually I did add a test in 38720b0

**Comment by fernahh** [comment]
@jdforsythe I'll close this PR. But, after update bower package to version v2.0.3 and the problem don't fix, we can reopen this. OK?

**Pull request closed without merging**
